### PR TITLE
Game room choices

### LINKED ISSUE #69: System randomizes answers on show game room
- [x] The system will get the correct track title based on the audio that's currently playing.
- [x] The system adds the correct track along with the other tracks on the room where the player is playing then shuffles the choices.
- [x] The answers are in a form of buttons.

### PR DESCRIPTION
**Pull request by yvettetan**
Closes #69 

- [x] Shuffles tracks in rooms controller(show action) to ensure tracks are played randomly when room is visited
- [x] Hides start game button on click
- [x] Displays question and buttons for choices when game starts
- [x] Creates chocies.js file to fetch tracks using room.id and handle display of random choices
- [x] Creates specs

Screen Shot 2021-09-27 at 7 52 00 PM

Preview: 

https://user-images.githubusercontent.com/78162620/134903835-f5bd4118-cbce-455e-9734-6a15f7ddeb74.mov

### CODE REVIEW

**Review by lea927 — APPROVED** [review]
This is so fun to test. Great job Yvette! <3

**Review by annagabriel-hash — COMMENTED** [review]
As discussed, I think it's better to separate all the functions related to the data and all the functions related to the view :) Then, create another function to merge the two similar to MVC concept :)

**Review by annagabriel-hash — APPROVED** [review]
All good!! Nice work, yvette 💯  Had fun trying it out. Great job in designing it as well 🤩🤩🤩

**Comment by yvettetan** [comment]
@annagabriel-hash Thanks for the suggestions, appreciate it! 😊

**Pull request merged**
